name: ğŸ“ Latest Dev.to Blog Posts

on:
  schedule:
    - cron: '0 */12 * * *' # Every 12 hours
  workflow_dispatch: # Manual trigger

permissions:
  contents: write # Needed to update the README

jobs:
  update-readme-with-blog:
    name: ğŸ”„ Update README with latest blogs
    runs-on: ubuntu-latest

    steps:
      - name: â¬‡ï¸ Checkout repo
        uses: actions/checkout@v4

      - name: ğŸ“° Fetch and insert latest Dev.to posts
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: 'https://dev.to/feed/maurya-sachin'
          max_post_count: 3
          commit_message: 'âœ¨ update: latest Dev.to blog posts in README'
