name: Format README

on:
  schedule:
    - cron: "0 18 * * *"
  workflow_dispatch:

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run Prettier
        uses: creyD/prettier_action@v3.3
        with:
          prettier_options: "--write README.md"

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Auto-format README"
          commit_user_name: "maurya-sachin"
          commit_user_email: "sachinmaurya1710@gmail.com"
