name: GitHub Metrics

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: "header, activity, community, repositories, metadata"
          plugin_languages: yes
          plugin_achievements: yes
          plugin_codesize: yes
          config_timezone: Asia/Kolkata
          filename: github-metrics.svg

      - name: Commit generated metrics (ensure commit counted)
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update github-metrics.svg"
          commit_user_name: "maurya-sachin"
          commit_user_email: "sachinmaurya1710@gmail.com"
